### ISSUE TITLE
Questionable Accuracy

### ISSUE THREAD

**Issue by joshuasmith44** [joehoeller/Object-Detection-on-Thermal-Images#11]
Hello I have been working with this dataset and was not able to achieve a mAP of > .9 on the validation set. However, according to your custom.data file you are training and validating/testing on the same dataset. I wanted to confirm my suspicion that the mAP you are quoting was on the same dataset that you trained on. Thanks.

**Comment by FranciscoReveriano** [comment]
I have personally only gotten close to .7 with a custom build model. 
.9 seems a bit farfetched.

**Comment by MoatazElTahan** [comment]
I see the achieved percentage very weird because there aren't any published papers that stated a precision higher than 82% on FLIR dataset

**Comment by joehoeller** [comment]
The chart that is generated shows the accuracy score. Several other people have downloaded it and got same results as repo. There is a disclaimer on how to reproduce data science results in the readme.md file.

**Comment by joehoeller** [comment]
@FranciscoReveriano lets connect on screen share and I’ll show you on my system after the holiday.
