### ISSUE TITLE
Source 0 not working

### ISSUE THREAD

**Issue by yaviga** [joehoeller/Object-Detection-on-Thermal-Images#12]
Hi,

I have a raspberry pi camera attached to the jetson nano. Using other object recognition modules, the camera is working fine.

When I try this model with the below command I am getting the following message. Please help me urgently. Thanks!
python3 detect.py --source 0
Namespace(agnostic_nms=False, augment=False, cfg='cfg/yolov3-spp.cfg', classes=None, conf_thres=0.3, device='', fourcc='mp4v', half=False, img_size=512, iou_thres=0.6, names='data/coco.names', output='output', save_txt=False, source='0', view_img=False, weights='weights/yolov3-spp-ultralytics.pt')
Using CUDA device0 _CudaDeviceProperties(name='NVIDIA Tegra X1', total_memory=3964MB)

Model Summary: 225 layers, 6.29987e+07 parameters, 6.29987e+07 gradients
1/1: 0..
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (1757) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Internal data stream error.
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (886) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
VIDEOIO ERROR: V4L: Unable to get camera FPS
 success (3264x2464 at 99.00 FPS).

After this, one Full dark green popup window opens. I could not see anything except the green color. Please advise if I need to install anything for GStreamer.

**Comment by joehoeller** [comment]
I’m sorry but this was never intended to run on Jetson. This is out of scope for this project; My advice is to fork it and modify it for Jetson.

**Comment by yaviga** [comment]
Hi Joe,

I tested this module using video & images from the local jetson nano directory(/data/samples) . It works perfectly in Jetson Nano. Do you mean that this module does not support only the live cameras like raspberry pi camera/other IP cameras?
My OS is 
Ubuntu 18.04.5 LTS
Release:	18.04

How about the live streams like RTSP? I am trying with RTSP stream as well. 
IP Camera RTSP:  'rtsp://username:password@192.168.1.64/1'  # IP camera with login
Please recommend RTSP as well.

Thanks

**Comment by joehoeller** [comment]
I don’t know, I’ve never used it for that.
