### ISSUE TITLE
how do i train the model on the 16 bit tiff files?

### ISSUE THREAD

**Issue by joel5638** [joehoeller/Object-Detection-on-Thermal-Images#2]
@joehoeller Please help with training of the 16 bit thermal images.  What are the arguments that are needed to pass to run the train.py?

please help, thank you

**Comment by joehoeller** [comment]
@joel5638 - 
If you want to train a model from scratch go to the README and click the link to Ultralytics YOLO. 

Torch doesn’t support .tiff so you’ll have to do this hacky workaround:


from torchvision.datasets import ImageFolder
from torchvision.datasets.folder import IMG_EXTENSIONS

len(ImageFolder("/tmp/test/"))  

IMG_EXTENSIONS.append('tiff')

len(ImageFolder("/tmp/test/"))

**Comment by FranciscoReveriano** [comment]
I would recommend making your own functions. Since the pixel normalization is very important.

**Comment by joel5638** [comment]
@joehoeller Thank you. How do i perform these steps? I mean where do I add these lines in scripts in? In the train.py  file?

**Comment by joehoeller** [comment]
Before your pipe
