### ISSUE TITLE
Classes error. AssertionError: Model accepts 18 classes labeled from 0-17, however you labelled a class 18.

### ISSUE THREAD

**Issue by joel5638** [joehoeller/Object-Detection-on-Thermal-Images#3]
UNable to process training as the error says this.

AssertionError: Model accepts 18 classes labeled from 0-17, however you labelled a class 18.
![Screenshot from 2020-02-25 09-42-32](https://user-images.githubusercontent.com/38422983/75214703-7365c280-57b4-11ea-8df3-8978d11d7e30.png)

**Comment by LevineYang** [comment]
Same error, got any idea how to solve?

**Comment by joel5638** [comment]
reduce filters to filters=[4 + 1 + n] * 3, where n is your class count. This modification should be made to the layer preceding each of the 3 YOLO layers. Also modify classes=80 to classes=n in each YOLO layer, where n is your class count.

calculate your filters appropriately. classes = 18  then filters would be 69.
[4+1+18] *3 =  69.
update the same in all the three yolo layers in the .cfg file.

reference:https://github.com/ultralytics/yolov3/wiki/Train-Custom-Data

**Comment by joehoeller** [comment]
Please close issue if that is the accepted answer.
