### ISSUE TITLE
 About training datasets

### ISSUE THREAD

**Issue by ycdhqzhiai** [joehoeller/Object-Detection-on-Thermal-Images#4]
@joehoeller Thank you for your work.Which training datates do you use has 18 classe and mAP=0.961

https://github.com/joehoeller/Object-Detection-on-Thermal-Images/blob/7ef5514d2491600c4aceafa31e8603eb6ec08909/data/custom.data#L1

**Comment by ycdhqzhiai** [comment]
FLIR Thermal Images Dataset have only five category
![image](https://user-images.githubusercontent.com/12273405/80340354-10b3a480-8893-11ea-9884-08563becf4fa.png)

**Comment by silver-deguz** [comment]
@ycdhqzhiai I wonder this too. Also asked a different question as to if there was supplemental images on top of the FLIR dataset.

**Comment by joehoeller** [comment]
the flir dataset changed and i have to update Dark Chocolate rerpo as well, I just have not had time. However, this is open src and that is the beauty of it. You are free to contrib to update the software. Or you wait until I have time, which i am sorry to say, isnt looking like anytime soon for me.

**Comment by joehoeller** [comment]
> @ycdhqzhiai I wonder this too. Also asked a different question as to if there was supplemental images on top of the FLIR dataset.

there were no supplemental images; have you downloaded the pre-trained model?

**Comment by joehoeller** [comment]
> @joehoeller Thank you for your work.Which training datates do you use has 18 classe and mAP=0.961
> 
> https://github.com/joehoeller/Object-Detection-on-Thermal-Images/blob/7ef5514d2491600c4aceafa31e8603eb6ec08909/data/custom.data#L1

yes it was set to 18 classes but the previous (outdated version) of the flir dataset only had 3 of the classes, so that is all the pre-trained model learned. you can take the pre-trained model and do transfer learning on it: https://github.com/ultralytics/yolov3/wiki/Example:-Transfer-Learning
