### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by ChunmianLin** [joehoeller/Object-Detection-on-Thermal-Images#5]
Hi, could you please upload a piece of data of FLIR? I could not download in the official website or Google Drive.
Thanks a lot !

**Comment by FranciscoReveriano** [comment]
Can you send the link of the official website?

**Comment by ChunmianLin** [comment]
Yes, but my network cannot access to some website and google drive, and dataset doesn't download successfully. Could you please upload the whole dataset on your project or Baiduyun Drive?
Thanks a lot!

**Comment by joehoeller** [comment]
GitHub prevents file uploads >100mb

**Comment by joehoeller** [comment]
Please close this issue

**Comment by joehoeller** [comment]
> Can you send the link of the official website?

Link: https://www.flir.com/oem/adas/adas-dataset-form/

**Comment by ChunmianLin** [comment]
@joehoeller Thanks. I have got it.
