### ISSUE TITLE
Classes Used + Pretrained Weights

### ISSUE THREAD

**Issue by silver-deguz** [joehoeller/Object-Detection-on-Thermal-Images#6]
Not so much an issue, but curious as to if you used all 80 COCO classes since the FLIR dataset contains only 5 classes. Or did you supplement the FLIR dataset with additional thermal images?

Also, did you train the model from scratch or fine-tune?

**Comment by joehoeller** [comment]
Trained from scratch, and you are correct the dataset only had so many classes despite being trained for 18.
