### ISSUE TITLE
about the "Improved IOU Calculation"

### ISSUE THREAD

**Issue by Yidann** [joehoeller/Object-Detection-on-Thermal-Images#7]
Hello,I wonder where is the "Improved IOU Calculation" is used as the acticle described?
Is it used in loss calculation? I saw the IOU calculation in [this code](https://github.com/joehoeller/Object-Detection-on-Thermal-Images/blob/7ef5514d2491600c4aceafa31e8603eb6ec08909/utils/utils.py#L245) which I think is not the version described in the article. Did I missed something?
Thank you!

**Comment by joehoeller** [comment]
No it was the addt’l repo Dark Chocolate 🍫 that created the bounding box coords with diff, but more accurate calculations.
